# Generated by Django 5.2.5 on 2025-08-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerbside_id', models.CharField(max_length=50)),
                ('zone_number', models.CharField(max_length=20)),
                ('status_description', models.CharField(max_length=50)),
                ('status_timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'parkings',
            },
        ),
    ]
