# Generated by Django 5.2.5 on 2025-08-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionBoundary',
            fields=[
                ('regionId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('stateCode', models.CharField(db_index=True, max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('geometry', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorVehicleCensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('vehicleCount', models.BigIntegerField()),
                ('growthRate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'year'], name='insights_mo_state_1eb2da_idx')],
                'unique_together': {('state', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RegionalPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa2', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop', to='insights.regionboundary')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'region'], name='insights_re_year_32390f_idx'), models.Index(fields=['sa2'], name='insights_re_sa2_39db1e_idx')],
                'unique_together': {('region', 'year')},
            },
        ),
    ]
