# Generated by Django 5.2.5 on 2025-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimRegion',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_code', models.CharField(max_length=64, unique=True)),
                ('region_name', models.CharField(max_length=255)),
                ('region_type', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_region_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAbsPopulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_year', models.IntegerField()),
                ('population_total', models.IntegerField()),
                ('population_male', models.IntegerField(blank=True, null=True)),
                ('population_female', models.IntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('load_batch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_abs_population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAbsVehicleCensus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_year', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, max_length=128, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=128, null=True)),
                ('vehicle_count', models.IntegerField()),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('load_batch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_abs_vehicle_census',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MotorVehicleCensus',
        ),
        migrations.DeleteModel(
            name='RegionalPopulation',
        ),
        migrations.DeleteModel(
            name='RegionBoundary',
        ),
    ]
